# Generated by Django 2.2.4 on 2019-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUAPP', '0002_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_name',
            name='title_logo',
            field=models.CharField(max_length=30, verbose_name='logo'),
        ),
    ]
